// <auto-generated />
using System;
using Chillout.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chillout.Migrations
{
    [DbContext(typeof(DbContext1))]
    partial class DbContext1ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Chillout.DataAccess.Core.Models.PassListRto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassWord")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PassList");
                });

            modelBuilder.Entity("Chillout.DataAccess.Core.Models.UserRto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PassListRtoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassWord")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PassListRtoId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Chillout.DataAccess.Core.Models.UserRto", b =>
                {
                    b.HasOne("Chillout.DataAccess.Core.Models.PassListRto", "PassListRto")
                        .WithMany("Users")
                        .HasForeignKey("PassListRtoId");
                });
#pragma warning restore 612, 618
        }
    }
}
